language: ruby
bundler_args: --without development
script: "bundle exec rake"
env:
  - CI=true
rvm:
  - jruby-20mode
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
notifications:
  recipients:
    - smaginsergey1310@gmail.com
branches:
  only:
    - master
